version: '3.8'
services:
  stunnel-server:
    build:
      context: ./server
    networks:
      stunnel-net:
        ipv4_address: 172.20.0.2

  stunnel-client:
    build:
      context: ./client
    networks:
      stunnel-net:
        ipv4_address: 172.20.0.3

networks:
  stunnel-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
